# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b87fa14c2bc8232ab4738fc512a7b868106d16af773404e6fc7c649d8cb7852409446f22648aca3c49242b038379febdce1113139309aa0ab1217761605ec61a

test:
  secret_key_base: 19352b37988930e9b75eabf517b066958209d5585b25485563f462d36492d043aa505441efa6bcf0e8222a41b657f9c78b80c22e50f167bced39ae815aacbb26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
